name: deploy-to-aws
run-name: ${{ github.actor }} ESTA HACIENDO DEPLOY A PRODUCCIÓN  🤞
on: 
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install AWS CLI
        run: |
          sudo apt-get update && \
          sudo apt-get install -y python3-pip && \
          pip3 install --upgrade --user awscli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install esbuild
        run: |
          npm i -g esbuild
          npm i 
      - name: Build
        run: |
          sam build -p --beta-features
      - name: Deploy
        run: |
          ENVIRONMENT=prod
          CI_PROJECT_NAME=bff-sip-api
          STACK=$ENVIRONMENT-$CI_PROJECT_NAME
          BUCKET=$STACK-deploy
          REGION_1=us-east-1
          sam deploy --no-confirm-changeset --s3-bucket $BUCKET --region $REGION_1 --stack-name $STACK --capabilities CAPABILITY_NAMED_IAM --parameter-overrides Environment=$ENVIRONMENT